---
- name: vm-configure
  hosts: 127.0.0.1
  connection: local
  roles:
    - common
    - aws-cli
    - azure-cli
    - gcloud-cli
    - docker
    - powershell
    # - k3s
    - xubuntu-desktop
    # - xubuntu-desktop-customizations